version: '3.3'

services:
  web:
    build: .
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .docker.env
    ports:
      - '5500:5500'
    environment:
      - PORT=5500
  migration:
    build:
      context: .
      dockerfile: migration.Dockerfile
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .docker.env
    volumes:
      - ./prisma:/home/app/prisma
  database:
    image: postgres:14
    env_file:
      - .docker.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - blog-cms-api-data:/var/lib/postgresql/data
volumes:
  blog-cms-api-data:
